sudo: false
language: python
python: 
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - redis-server
install:
  - pip install tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
env:
  - TOXENV=flake8
  - TOXENV=docs
